#!/usr/bin/env bash
#
# https://repo2docker.readthedocs.io/en/latest/config_files.html#postbuild-run-code-after-installing-the-environment
set -e


pip install .
jupyter labextension install jupyterlab-jupytext
